### ISSUE TITLE
MCDU Server down

### ISSUE THREAD

**Issue by simson166** [flybywiresim/a32nx#6897]
### Aircraft Version

Experimental

### Build info

```json
{
  "built": "2022-03-12T02:33:41+00:00",
  "ref": "experimental",
  "sha": "a5960504d0b5fdee28a1169718cdc1c379caca5e",
  "actor": "Saschl",
  "event_name": "manual",
  "pretty_release_name": "experimental:a5960504"
}
 or
{
  "built": "2022-03-12T06:04:05+00:00",
  "ref": "master",
  "sha": "3cd7597b680cb48b874f401bfa03d4d63bee7dfa",
  "actor": "tracernz",
  "event_name": "manual",
  "pretty_release_name": "master:3cd7597b"
}
```

### Describe the bug

Since the last update, the MCDU server does not work with Dev. and Exp. versions.
dep Version: 3cd7597 and Exp. Version: a596050

### Expected behavior

working MCDU server as usual

### Steps to reproduce

The server starts as usual, after a response to the printer request (yes or no, it doesn't matter) the server is gone

**Comment by gizmo71** [comment]
```
Starting server...
C:\snapshot\external\node_modules\wmic\index.js:184
        var wm = execFile('wmic', splitter(cmd), opts),
                 ^

TypeError: execFile is not a function
    at C:\snapshot\external\node_modules\wmic\index.js:184:18
    at C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:3669:28
    at eachOfArrayLike (C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:506:13)
    at eachOf (C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:626:16)
    at awaitable (C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:211:32)
    at C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:3668:9
    at awaitable (C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:211:32)
    at Object.parallel (C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:3839:16)
    at C:\snapshot\external\node_modules\wmic\index.js:167:9
    at C:\snapshot\external\node_modules\wmic\node_modules\async\dist\async.js:4011:13
```

**Comment by tracernz** [comment]
saschl has already submitted and merged a PR on the upstream package that broke https://github.com/tomas/wmic/pull/18

**Comment by taz8707** [comment]
Note that this error not only happens on de Experimental version, but on the Development version as wel.
